export const ERROR_STATUS_CODE = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  IM_A_TEAPOT: 418,
};

export const ERROR_MESSAGES = {
  [ERROR_STATUS_CODE.BAD_REQUEST]: "Yêu cầu không hợp lệ.",
  [ERROR_STATUS_CODE.UNAUTHORIZED]:
    "Bạn cần đăng nhập để thực hiện hành động này.",
  [ERROR_STATUS_CODE.FORBIDDEN]: "Bạn không có quyền truy cập tài nguyên này.",
  [ERROR_STATUS_CODE.NOT_FOUND]: "Không tìm thấy tài nguyên yêu cầu.",
  [ERROR_STATUS_CODE.CONFLICT]: "Dữ liệu đã tồn tại trong hệ thống.",
  [ERROR_STATUS_CODE.UNPROCESSABLE_ENTITY]: "Dữ liệu không thể xử lý được.",
  [ERROR_STATUS_CODE.INTERNAL_SERVER_ERROR]: "Lỗi hệ thống máy chủ.",
  [ERROR_STATUS_CODE.IM_A_TEAPOT]: "Tôi là một chiếc ấm trà!",
  AUTH_INVALID: "Email, số điện thoại hoặc mật khẩu không chính xác.",
  AUTH_TOKEN_INVALID: "Token không hợp lệ hoặc đã bị thu hồi.",
  AUTH_TOKEN_EXPIRED: "Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại.",
  VALIDATION_ERROR: "Dữ liệu không đúng định dạng Schema.",
};

export const VALIDATION_MESSAGES = {
  ID_INVALID: "ID không đúng định dạng UUID.",
  NAME_REQUIRED: "Tên không được để trống.",
  NAME_MIN: "Tên quá ngắn (tối thiểu 2 ký tự).",
  NAME_MAX: "Tên quá dài (tối đa 40 ký tự).",
  EMAIL_INVALID: "Email không đúng định dạng.",
  PHONE_INVALID: "Số điện thoại phải từ 10-11 chữ số.",
  PASSWORD_MIN: "Mật khẩu phải có ít nhất 6 ký tự.",
  TIER_INVALID: "Hạng khách hàng không hợp lệ.",
  POINTS_INVALID: "Điểm phải là một con số.",
  POINTS_NON_NEGATIVE: "Điểm không được là số âm.",
  ROLE_INVALID: "Vai trò nhân viên không hợp lệ.",
  USER_TYPE_INVALID: "Loại người dùng không hợp lệ.",
  TOKEN_REQUIRED: "Token không được để trống.",
  ITEMS_MIN: "Đơn hàng phải có ít nhất 1 sản phẩm.",
  ORDER_ITEMS_REQUIRED: "Đơn hàng phải có sản phẩm.",
  STAFF_STORE_REQUIRED: "Phải gán nhân viên vào một chi nhánh",
  HOTLINE_INVALID: "Hotline phải là 10 số",
  LOCATIONS_REQUIRED: "Phải cung cấp danh sách tọa độ",
  DATE_FORMAT_INVALID: "Định dạng ngày phải là YYYY-MM-DD",
  ORDERS_REQUIRED: "Danh sách đơn hàng không được trống",
  PIN_INVALID: "Mã PIN phải có 6 số",
};
