
export const MODELS = {
    auditLog: "auditLog",
    user: "user",
    refreshToken: "refreshToken",
    staff: "staff",
    customer: "customer",
    category: "category",
    product: "product",
    optionGroup: "optionGroup",
    productOption: "productOption",
    productOptionGroup: "productOptionGroup",
    productOptionValue: "productOptionValue",
    store: "store",
    order: "order",
    orderItem: "orderItem",
    orderItemOption: "orderItemOption",
    payment: "payment",
    refund: "refund",
    deliveryOrder: "deliveryOrder",
    deliveryEvent: "deliveryEvent",
    pointTransaction: "pointTransaction",
    voucher: "voucher",
    customerVoucher: "customerVoucher",
    voucherRedemption: "voucherRedemption",
};