services:
  db:
    image: postgres:16
    container_name: foodapp
    restart: unless-stopped
    environment:
      POSTGRES_DB: foodapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - foodapp_pgdata:/var/lib/postgresql/data
      - ./prisma/migrations/20260327152046_init/migration.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  foodapp_pgdata: