
@baseUrl = http://localhost:5001
/*
tạo user + customer 
*/
POST {{baseUrl}}/api/v1/auth/register/customer
Content-Type: application/json
{
  "phone": "0909123456",
  "password": "Password123@",
  "name": "Nguyễn Văn Khách",
  "email": "khachhang@gmail.com"
}

POST http://localhost:5001/api/v1/auth/register/staff
Content-Type: application/json
{
  "phone": "0337104445",
  "password": "manager123",
  "name": "Nguyễn Văn Quản Lý",
  "email": "manager@foodapp.com",
  "storeId": "f6088716-ca5e-4ed0-bef4-3dfe3abb51b8",
  "role": "MANAGER"
}
/*
tạo user + staff  
*/
POST {{baseUrl}}/api/v1/auth/register/staff
Content-Type: application/json
{
  "email": "cashier.hcm01@trasua.com",
  "phone": "0988111222",
  "password": "StaffPassword789",
  "storeId": "f6088716-ca5e-4ed0-bef4-3dfe3abb51b8", 
  "role": "CASHIER"
}

POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json
{
  "identifier": "cashier.hcm01@trasua.com",
  "password": "StaffPassword789"
}

### Login API
# @name login
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "customer@foodapp.com",
  "password": "customer123"
}


### Login API
# @name login
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "manager@foodapp.com",
  "password": "manager123"
}

POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json
{
  "identifier": "admin@foodapp.com",
  "password": "admin123"
}

###

### Logout API
# @name logout
POST {{baseUrl}}/api/v1/auth/logout
Authorization: Bearer {{accessToken}}
Cookie: refreshToken={{refreshToken}}
Content-Type: application/json

{
  "message": "User logout"
}

### 2. Test Refresh Token (Thành công)
# @name refreshTokenSuccess
# @forceIt
POST {{baseUrl}}/api/v1/auth/refresh-token
Cookie: refreshToken={{refreshToken}}
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)

{{
  // Sau khi refresh thành công, chúng ta phải cập nhật lại biến
  // vì RT cũ đã bị "Revoke" trong DB (Token Rotation)
  
  if (response.parsedBody && response.parsedBody.data) {
    exports.accessToken = response.parsedBody.data.accessToken;
    console.log("New Access Token captured");
  }

  const setCookie = response.headers['set-cookie'];
  if (setCookie) {
    const match = setCookie[0].match(/refreshToken=([^;]+)/);
    if (match) {
      exports.refreshToken = match[1];
      console.log("New Refresh Token captured (Rotation works!)");
    }
  }
}}

###

### 3. Test Refresh Token (Thất bại - Gửi token cũ đã bị xoay vòng)
# @name refreshTokenFail
POST {{baseUrl}}/api/v1/auth/refresh-token
Cookie: refreshToken=this_is_a_fake_or_expired_token
Content-Type: application/json

###

### 4. Lấy thông tin cá nhân
# @name getProfileWithNewToken
GET {{baseUrl}}/api/v1/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzk4YTQzOC01MDdlLTRmOTYtYmFlMy0yNWE1NTE5MTMwZTgiLCJ0eXBlIjoiU1RBRkYiLCJyb2xlIjoiTUFOQUdFUiIsInNpZCI6ImNjYjc2YWRmLWYxMGUtNDQyYi1iNThlLTJmZWEwZDRkNWVhMyIsInN0b3JlSWQiOiI4MjM4ZGY1ZS1jMTdlLTQ1ZGEtYmFlYi0zMmFmMGNmYzQyOGYiLCJpYXQiOjE3NzU4MzgwOTEsImV4cCI6MTc3NTg0MTY5MX0.Yq_I9ZCmLN7hW8rBiN8PDyoJE7h_yWBy398kGA3RJ_s
