@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzODA2YTA3NS1hNThiLTQwM2YtOGEyMS1hNDcyOWYxNTk0MjIiLCJ0eXBlIjoiU1RBRkYiLCJyb2xlIjoiTUFOQUdFUiIsInNpZCI6IjhhZDlhNjU4LWQ3YWUtNDkyZi05OTI4LTVlOGVhOTFlNTVlZSIsInN0b3JlSWQiOiIwZDgxYWU5My1hYmM5LTRhOWYtOGUyYy01Y2MyZmIwNzZkNmYiLCJpYXQiOjE3ODA2MzgyNTksImV4cCI6MTc4MDY0MTg1OX0.u38z2SEKCho7om-sHHJSiylGyfATLaY7YcK28JVAwI4
@refreshToken = 0c7f9b48-14c9-4244-8db7-0c72df73e020

###
/*
tạo user + customer 
*/
POST http://localhost:5001/api/v1/auth/register
Content-Type: application/json

{
  "phone": "09337104446",
  "password": "Password123@",
  "name": "Thien Phuc",
  "email": "phuclnt22@gmail.com"
}

###
POST http://localhost:5001/api/v1/auth/register
Content-Type: application/json

{
  "phone": "0123456789",
  "password": "admin@123",
  "name": "Admin",
  "email": "admin@gmail.com"
}

###
POST http://localhost:5001/api/v1/internal/auth/register/guest
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "phone": "0988888888",
  "name": "Nguyen Van Guest"
}

###
/*
tạo user + staff
*/
POST http://localhost:5001/api/v1/internal/auth/register/staff
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "cashier2.hcm01@trasua.com",
  "phone": "0988111223",
  "password": "StaffPassword789",
  "storeId": "58660bb9-cfd8-41f3-9cc6-989485b26d10", 
  "role": "CASHIER"
}

###
POST http://localhost:5001/api/v1/internal/auth/register/staff
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "admin@foodapp.com",
  "password": "admin@123",
  "storeId": "58660bb9-cfd8-41f3-9cc6-989485b26d10",
  "role": "ADMIN"
}


###
/*
login as customer
*/
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "09337104446",
  "password": "Password123@"
}

###
/*
login as staff
*/
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "admin@foodapp.com",
  "password": "admin123"
}

###
/*
login as manager
*/
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "manager@foodapp.com",
  "password": "manager123"
}

###
/*
login as admin
*/
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "admin@foodapp.com",
  "password": "admin123"
}

###
/*
login as kitchen staff
*/
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "kitchen1@foodapp.com",
  "password": "password123"
}

###
/*
login as shipper
*/
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "identifier": "test_shipper@foodapp.com",
  "password": "password123"
}

###
/*
logout
*/
# @name logout
POST http://localhost:5001/api/v1/auth/logout
Authorization: Bearer {{accessToken}}
Cookie: refreshToken={{refreshToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# @name getCustomerProfile
GET http://localhost:5001/api/v1/auth/profile
Authorization: Bearer {{accessToken}}

###
# @name getInternalProfile
GET http://localhost:5001/api/v1/internal/profile
Authorization: Bearer {{accessToken}}
