@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZmU3NjllNy1lNjlmLTQ4NjMtOTU3NS1iOTZmZDQ0ZDUzOGQiLCJ0eXBlIjoiQ1VTVE9NRVIiLCJjaWQiOiI1MDY4MmM2OC05YzAyLTRhNmItOTdhMi0zMzAxMDc5MmI3ZTYiLCJpYXQiOjE3ODAzMTAxODAsImV4cCI6MTc4MDMxMzc4MH0.qYuf5nWP7mJ4L0xA0Zt1cmbOQJs8lNNieyehlVd9Fiw
@refreshToken = 0c7f9b48-14c9-4244-8db7-0c72df73e020

###
/*
tạo user + customer 
*/
POST http://localhost:5001/api/v1/auth/register
Content-Type: application/json

{
  "phone": "09337104446",
  "password": "Password123@",
  "name": "Thien Phuc",
  "email": "phuclnt22@gmail.com"
}

POST http://localhost:5001/api/v1/auth/register
Content-Type: application/json

{
  "phone": "09337104445",
  "password": "Password@123",
  "name": "Thien Phuc",
  "email": "22110201@student.hcmute.edu.vn"
}

POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json
{
  "identifier": "22110201@student.hcmute.edu.vn",
  "password": "New@123"
}

POST http://localhost:5001/api/v1/auth/forgot_password_otp
Content-Type: application/json
{
  "email": "22110201@student.hcmute.edu.vn"
}


POST http://localhost:5001/api/v1/auth/reset_password_otp
Content-Type: application/json
{
  "email": "22110201@student.hcmute.edu.vn",
  "code": "770000",
  "newPassword": "New@123"
}

POST http://localhost:5001/api/v1/auth/verify_forgot_password_otp
Content-Type: application/json
{
  "email": "22110201@student.hcmute.edu.vn",
  "code": "770000"
}