@baseUrl = http://localhost:5001

### Get Users List (Admin/Manager only)
GET {{baseUrl}}/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzk4YTQzOC01MDdlLTRmOTYtYmFlMy0yNWE1NTE5MTMwZTgiLCJ0eXBlIjoiU1RBRkYiLCJyb2xlIjoiTUFOQUdFUiIsInNpZCI6ImNjYjc2YWRmLWYxMGUtNDQyYi1iNThlLTJmZWEwZDRkNWVhMyIsInN0b3JlSWQiOiI4MjM4ZGY1ZS1jMTdlLTQ1ZGEtYmFlYi0zMmFmMGNmYzQyOGYiLCJpYXQiOjE3NzYyNDg0NzMsImV4cCI6MTc3NjI1MjA3M30.h_gV89-avYBrSAjg2DFGF9DKaUZDhfFl_4bTBkoq7gU
Content-Type: application/json

###

### Get User by ID
GET {{baseUrl}}/api/v1/users/550e8400-e29b-41d4-a716-446655440000
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

### Update User
PUT {{baseUrl}}/api/v1/users/550e8400-e29b-41d4-a716-446655440000
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Nguyễn Văn A",
  "phone": "0909123456",
  "email": "updated@gmail.com"
}

